name: Create Release



on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Get version from manifest.json
        id: get_version
        run: |
          VERSION=$(jq -r .version manifest.json)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Version found: $VERSION"

      - name: Check if tag exists
        id: check_tag
        run: |
          TAG="v${{ steps.get_version.outputs.VERSION }}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists. Skipping release creation."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create and push tag
        if: steps.check_tag.outputs.exists == 'false'
        run: |
          TAG="v${{ steps.get_version.outputs.VERSION }}"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "$TAG"
          git push origin "$TAG"

      - name: Build extension
        run: |
          npx web-ext build --overwrite-dest

      - name: Sign extension
        run: |
          npx web-ext sign --channel=unlisted --api-key=${{secrets.AMO_JWT_ISSUER}}  --api-secret=${{secrets.AMO_JWT_SECRET}}

      - name: Create Release
        if: steps.check_tag.outputs.exists == 'false'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          files: web-ext-artifacts/*.zip, web-ext-artifacts/*.xpi
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
